apiVersion: v1
kind: Service
metadata:
  name: images-gallery-frontend-services
spec:
  selector:
    app: images_gallery_frontend
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 3000
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: images-gallery-frontend-deployment
spec:
  selector:
    matchLabels:
      app: images_gallery_frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: images_gallery_frontend
    spec:
      containers:
      - name: images-gallery-frontend-container
        image: rrmavani/images_gallery_frontend:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
