apiVersion: v1
kind: Service
metadata:
  name: images-gallery-frontend-services
spec:
  selector:
    app: images_gallery_frontend
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 3000
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: images-gallery-api-services
spec:
  selector:
    app: images_gallery_api
  ports:
  - protocol: "TCP"
    port: 5050
    targetPort: 5050
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-express-services
spec:
  selector:
    app: mongo-express
  ports:
  - protocol: "TCP"
    port: 8081
    targetPort: 8081
  type: NodePort


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: images-gallery-frontend-deployment
spec:
  selector:
    matchLabels:
      app: images_gallery_frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: images_gallery_frontend
    spec:
      containers:
      - name: images-gallery-frontend-container
        image: rrmavani/images_gallery_frontend:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: "http://images-gallery-api-services:5050"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: images-gallery-api-deployment
spec:
  selector:
    matchLabels:
      app: images_gallery_api
  replicas: 2
  template:
    metadata:
      labels:
        app: images_gallery_api
    spec:
      containers:
      - name: images-gallery-api-container
        image: rrmavani/images_gallery_api:v5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5050


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
spec:
  selector:
    matchLabels:
      app: mongo-express
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: password
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongo
